name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        # Install pylint
        sudo apt update -qq && sudo apt install -qq python-pip python-virtualenv
        virtualenv ~/venv
        source ~/venv/bin/activate
        pip install --quiet astroid==1.1.0 pylint==1.1.0
        # Download Eclipse SDK
        eclipse_tar="ci-dep-eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz"
        eclipse_tar_path="${HOME}/${eclipse_tar}"
        mx.live-programming/utils.sh download-asset "${eclipse_tar}" 0.8.0 "${eclipse_tar_path}"
        tar -xzf ${eclipse_tar_path} -C ${HOME}
        echo "::set-env name=ECLIPSE_EXE::${HOME}/eclipse/eclipse" # required by mx
        # Download ECJ
        mx.live-programming/utils.sh download-asset "ci-dep-ecj-4.5.2.jar" 0.8.0 "${HOME}/ecj.jar"
        echo "::set-env name=JDT::${HOME}/ecj.jar" # required by mx
        # Set up mx, oracle/graal, and LabsJDK11
        mx.live-programming/utils.sh set-up-mx
        mx.live-programming/utils.sh shallow-clone-graal
        mx.live-programming/utils.sh set-up-labsjdk11 ~/
    - name: Run 'mx checkcopyrights'
      run: mx checkcopyrights --primary -- --projects src,mx.live-programming
    - name: Run 'mx gate'
      run: |
        source ~/venv/bin/activate
        export DEFAULT_DYNAMIC_IMPORTS=live-programming,/tools
        export FORCE_BASH_LAUNCHERS=polyglot
        mx gate --strict-mode