name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
    - name: Set up dependencies
      run: |
        pip install --quiet pylint==2.4
        # Download Eclipse SDK
        eclipse_tar="ci-dep-eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz"
        eclipse_tar_path="${HOME}/${eclipse_tar}"
        mx.live-programming/utils.sh download-asset "${eclipse_tar}" 0.8.0 "${eclipse_tar_path}"
        tar -xzf ${eclipse_tar_path} -C ${HOME}
        echo "ECLIPSE_EXE=${HOME}/eclipse/eclipse" >> "${GITHUB_ENV}" # required by mx
        # Download ECJ
        mx.live-programming/utils.sh download-asset "ci-dep-ecj-4.5.2.jar" 0.8.0 "${HOME}/ecj.jar"
        echo "JDT=${HOME}/ecj.jar" >> "${GITHUB_ENV}" # required by mx
        # Set up mx, oracle/graal, and LabsJDK11
        mx.live-programming/utils.sh set-up-mx
        mx.live-programming/utils.sh shallow-clone-graal
        mx.live-programming/utils.sh set-up-labsjdk11 ~/
    - name: Run 'mx checkcopyrights'
      run: mx checkcopyrights --primary -- --projects src,mx.live-programming
    - name: Run 'mx gate'
      run: |
        export DEFAULT_DYNAMIC_IMPORTS=live-programming,/tools DISABLE_INSTALLABLES=false FORCE_BASH_LAUNCHERS=polyglot
        mx gate --strict-mode
